name: Check for Secrets
on: [push, pull_request] # Optional to set for any github action

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        with:
          config: ''
          repo: ${{ github.repository }}
          commit: ${{ github.sha }}
