name: TruffleHog Check
on:
  pull_request:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    - name: Install truffleHog
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install truffleHog

    - name: Run TruffleHog
      run: trufflehog git file://github///github/workspace
